service: cmc4-config-convention

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30

  stage: dev
  region: us-east-2

  environment:
    S3_BUCKET: cmc4-config
    S3_PREFIX: conventions/
    S3_EXTENSION: .json
    IDENTITY_KEY: conventionId
    METADATA_KEYS: author;editor

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "*"

functions:
  conventionPost:
    handler: handler.post

    events:
      - http:
          path: config/convention
          method: post

  conventionPut:
    handler: handler.put

    events:
      - http:
          path: config/convention/{conventionId}
          method: put  

plugins:
  - serverless-plugin-typescript
